name: Build PHP

on:
  push:
    branches: ["test", "prod"]
    tags: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger-deployment:
    uses: Middle-Earth-Gitops/build-laravel-app-image/.github/workflows/build-deploy-app.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
    secrets: inherit
